//! Myki CLI - Secure Command Line Interface
//! 
//! Provides technical users with direct access to the Myki vault from the terminal.
//! This CLI allows listing, searching, and adding credentials to an encrypted vault.
//! All cryptographic operations (Argon2id key derivation, AES-GCM encryption) are
//! delegated to the myki_core library for maximum security.

// ============================================================================
// IMPORTS
// ============================================================================
// External crate: Command-line argument parsing
// clap::Parser - derives a CLI parser from struct definitions
// clap::Subcommand - enables nested command structures (list, search, add)
use clap::{Parser, Subcommand};

// External crate: Secure password reading from terminal
// read_password() reads without echoing characters to the screen
use rpassword::read_password;

// Internal crate: Myki core library providing cryptographic functions
// VaultDatabase - encrypted SQLite database operations
// derive_key - Argon2id key derivation function
use myki_core::{VaultDatabase, derive_key};

// Standard library: Path handling for vault file location
use std::path::PathBuf;

use tracing_subscriber::{layer::SubscriberExt, util::SubscriberInitExt, EnvFilter};

// ============================================================================
// CLI STRUCTURE DEFINITION
// ============================================================================

/// Secure CLI for Myki Password Manager
/// 
/// This struct is parsed by clap to handle command-line arguments.
/// The #[derive(Parser)] attribute auto-generates parsing logic from the struct fields.
#[derive(Parser)]
// Customizes the CLI help text generated by clap
#[command(author, version, about, long_about = None)]
struct Cli {
    /// Path to the vault database file.
    /// 
    /// The vault is stored as an SQLite database with encrypted content.
    /// - short: Allows '-v <path>' shorthand
    /// - long: Allows '--vault <path>' full flag
    /// - default_value: Falls back to 'vault.db' in current directory
    #[arg(short, long, value_name = "FILE", default_value = "vault.db")]
    vault: PathBuf,

    /// The subcommand to execute (list, search, or add).
    /// 
    /// Clap automatically handles dispatching to the matching Commands variant.
    #[command(subcommand)]
    command: Commands,
}

/// Available CLI subcommands.
/// 
/// Each variant represents a different operation on the vault.
/// Clap automatically generates help text and shell completion scripts.
#[derive(Subcommand)]
enum Commands {
    /// Create a new vault database.
    /// 
    /// Prompts for a master password and creates an encrypted vault
    /// at the specified path. Use this before adding credentials.
    Create {
        /// Optional path for the vault database.
        /// 
        /// Defaults to 'vault.db' in the current directory.
        #[arg(short, long, value_name = "FILE")]
        vault: Option<PathBuf>,
    },
    
    /// List all credentials in the vault.
    /// 
    /// Displays a formatted table of all stored credentials showing
    /// title, username, and URL columns.
    List,
    
    /// Search for credentials matching a query string.
    /// 
    /// Performs a case-insensitive search across credential titles
    /// and usernames, displaying full details of matches.
    Search {
        /// The query string to search for.
        /// 
        /// Matches against both credential titles and usernames.
        query: String,
    },
    
    /// Add a new credential to the vault.
    /// 
    /// Prompts for the password securely, then encrypts and stores
    /// the new credential in the vault database.
    Add {
        /// Display title for the credential.
        /// 
        /// This is the human-readable name shown in lists (e.g., "GitHub", "AWS").
        title: String,
        
        /// Username for the account.
        /// 
        /// Typically an email address or username used to log in.
        username: String,
    },
}

// ============================================================================
// MAIN ENTRY POINT
// ============================================================================

/// Main entry point for the Myki CLI application.
/// 
/// # Execution Flow
/// 
/// 1. Parse command-line arguments using clap
/// 2. Validate vault file exists
/// 3. Securely read master password from terminal
/// 4. Derive encryption key using Argon2id KDF
/// 5. Open encrypted vault database
/// 6. Execute the requested command
/// 7. Clean up resources and return exit code
/// 
/// # Error Handling
/// 
/// Returns Err if:
/// - Vault file does not exist
/// - Password is incorrect (key derivation or decryption fails)
/// - Database operations fail
fn main() -> anyhow::Result<()> {
    // -----------------------------------------------------------------
    // Step 0: Initialize Logging
    // -----------------------------------------------------------------
    let log_dir = std::env::current_dir().unwrap_or_else(|_| PathBuf::from(".")).join("logs");
    let _ = std::fs::create_dir_all(&log_dir);
    let file_appender = tracing_appender::rolling::daily(&log_dir, "myki_cli.log");
    let (non_blocking, _guard) = tracing_appender::non_blocking(file_appender);

    tracing_subscriber::registry()
        .with(EnvFilter::try_from_default_env().unwrap_or_else(|_| EnvFilter::new("info")))
        .with(tracing_subscriber::fmt::layer().with_writer(non_blocking))
        .init();

    tracing::info!("Myki CLI Started");

    // -----------------------------------------------------------------
    // Step 1: Parse Command-Line Arguments
    // -----------------------------------------------------------------
    // Cli::parse() reads sys.argv and validates against the Cli struct
    // definition. It automatically handles --help, --version, and
    // generates structured error messages for invalid inputs.
    let cli = Cli::parse();

    // -----------------------------------------------------------------
    // Step 2: Validate Vault File Exists (for non-create commands)
    // -----------------------------------------------------------------
    // Check if the vault database file exists before attempting to open it.
    // PathBuf::exists() performs filesystem lookup without opening the file.
    // Skip this check for the Create command.
    if !matches!(&cli.command, Commands::Create { .. }) && !cli.vault.exists() {
        // Return early with formatted error message.
        // anyhow::anyhow! creates an error type that supports chaining.
        return Err(anyhow::anyhow!(
            "Vault does not exist at {:?}. Use 'create' command first.", 
            cli.vault
        ));
    }

    // -----------------------------------------------------------------
    // Step 3: Read Master Password Securely
    // -----------------------------------------------------------------
    // print! does NOT add a newline, allowing cursor to stay on same line.
    print!("Enter Master Password: ");
    
    // std::io::Write::flush ensures the prompt appears before read_password()
    // waits for input. Without this, output ordering is not guaranteed.
    std::io::Write::flush(&mut std::io::stdout())?;
    
    // read_password() reads from stdin without echoing characters.
    // This prevents the password from being visible on screen.
    let password = read_password()?;

    // -----------------------------------------------------------------
    // Step 4: Handle Create Command Separately
    // -----------------------------------------------------------------
    // The Create command doesn't need a vault file to exist yet.
    // We handle it before the unlock flow.
    if let Commands::Create { vault } = &cli.command {
        let vault_path = vault.clone().unwrap_or_else(|| PathBuf::from("vault.db"));
        
        // Check if vault already exists
        if vault_path.exists() {
            return Err(anyhow::anyhow!(
                "Vault already exists at {:?}. Delete it first to create a new one.",
                vault_path
            ));
        }
        
        // Prompt for master password
        print!("Enter new master password: ");
        std::io::Write::flush(&mut std::io::stdout())?;
        let password = read_password()?;
        
        print!("Confirm master password: ");
        std::io::Write::flush(&mut std::io::stdout())?;
        let confirm = read_password()?;
        
        if password != confirm {
            return Err(anyhow::anyhow!("Passwords do not match."));
        }
        
        if password.len() < 8 {
            return Err(anyhow::anyhow!("Password must be at least 8 characters."));
        }
        
        // Create the vault
        let db = VaultDatabase::create_new(vault_path.to_str().unwrap(), &password)
            .map_err(|e| anyhow::anyhow!("Failed to create vault: {}", e))?;
        
        db.close();
        println!("Vault created successfully at {:?}", vault_path);
        return Ok(());
    }
    
    // -----------------------------------------------------------------
    // Step 4: Derive Encryption Key from Password
    // -----------------------------------------------------------------
    // Open SQLite connection to read the salt from vault metadata.
    // The salt is stored unencrypted in the vault_meta table.
    // This is safe because the salt is not secret (only the password is).
    let conn = rusqlite::Connection::open(cli.vault.to_str().unwrap())
        .map_err(|e| anyhow::anyhow!("Failed to open vault database: {}", e))?;
    
    // Query the vault_meta table for the salt value.
    // The salt is stored as a Base64-encoded string.
    // 
    // query_row parameters:
    // - SQL query with ? placeholder
    // - [] = no query parameters
    // - closure: transforms row data into desired type
    let salt_b64: String = conn.query_row(
        "SELECT value FROM vault_meta WHERE key = 'salt'",
        [],
        |row| row.get(0),  // Get first (and only) column
    ).map_err(|e| anyhow::anyhow!(
        "Failed to get salt from vault: {}. Is the password correct?", e
    ))?;
    
    // Close the database connection before reopening with encrypted access.
    // This is required because SQLite doesn't support concurrent access
    // by multiple connections in all configurations.
    drop(conn);
    
    // Import the base64 trait for decode() method.
    // This allows calling .decode() on Base64 strings.
    use base64::Engine;
    
    // Decode the Base64-encoded salt back to raw bytes.
    // Base64 is used for safe text storage (avoids null bytes, control chars).
    let salt_vec = base64::engine::general_purpose::STANDARD
        .decode(salt_b64.as_bytes())
        .map_err(|e| anyhow::anyhow!("Invalid salt encoding: {}", e))?;
    
    // Validate salt length (must be exactly 32 bytes for Argon2id).
    // Argon2id requires a fixed-size salt for security.
    if salt_vec.len() != 32 {
        return Err(anyhow::anyhow!(
            "Invalid salt length: expected 32 bytes, got {}", 
            salt_vec.len()
        ));
    }
    
    // Convert Vec<u8> to [u8; 32] array for Argon2id.
    // Arrays have fixed size known at compile time, which is required
    // by the derive_key function signature.
    let mut salt_arr = [0u8; 32];
    salt_arr.copy_from_slice(&salt_vec);  // Copies exactly 32 bytes
    
    // Derive the master encryption key using Argon2id.
    // Argon2id is a memory-hard KDF resistant to GPU/ASIC attacks.
    // Default::default() uses safe parameters (memory, iterations, parallelism).
    let master_key = derive_key(&password, &salt_arr, &Default::default())
        .map_err(|e| anyhow::anyhow!(e.to_string()))?;

    // -----------------------------------------------------------------
    // Step 5: Open Encrypted Vault Database
    // -----------------------------------------------------------------
    // VaultDatabase::open() decrypts the database using the derived key.
    // If the key is wrong, decryption will fail with an error.
    let db = VaultDatabase::open(cli.vault.to_str().unwrap(), &master_key)
        .map_err(|e| anyhow::anyhow!(
            "Failed to open vault: {}. Is the password correct?", e
        ))?;

    // -----------------------------------------------------------------
    // Step 6: Execute Requested Command
    // -----------------------------------------------------------------
    // Pattern match on the command variant to dispatch to handlers.
    // This is the core functionality of the CLI.
    match &cli.command {
        // -----------------------------------------------------------------
        // Command: List all credentials
        // -----------------------------------------------------------------
        Commands::List => {
            // Retrieve all credentials from the vault.
            // get_all_credentials() decrypts and returns all entries.
            let creds = db.get_all_credentials()
                .map_err(|e| anyhow::anyhow!(e.to_string()))?;
            
            // Print formatted header row with column titles.
            // {:<20} = left-aligned, 20 characters wide
            println!("{:<20} {:<20} {:<20}", "Title", "Username", "URL");
            
            // Print separator line: "-" repeated 60 times
            println!("{}", "-".repeat(60));
            
            // Iterate and print each credential.
            // unwrap_or_default() handles optional URL field.
            for c in creds {
                println!(
                    "{:<20} {:<20} {:<20}", 
                    c.title, 
                    c.username, 
                    c.url.unwrap_or_default()
                );
            }
        }
        
        // -----------------------------------------------------------------
        // Command: Search credentials
        // -----------------------------------------------------------------
        Commands::Search { query } => {
            // Search by title or username using partial matching.
            let creds = db.search_credentials(query)
                .map_err(|e| anyhow::anyhow!(e.to_string()))?;
            
            // Print detailed view for each match.
            for c in creds {
                println!("--- {} ---", c.title);  // Section header
                println!("User: {}", c.username);
                println!("Pass: {}", c.password);
                if let Some(u) = c.url {  // Only print URL if present
                    println!("URL:  {}", u);
                }
            }
        }
        
        // -----------------------------------------------------------------
        // Command: Add new credential
        // -----------------------------------------------------------------
        Commands::Add { title, username } => {
            // Prompt for the credential password (not the vault master password).
            print!("Enter password for {}: ", title);
            std::io::Write::flush(&mut std::io::stdout())?;
            let cred_password = read_password()?;
            
            // Create a new Credential struct using the myki_core library.
            // Credential::new() handles initialization with timestamps, etc.
            let cred = myki_core::Credential::new(
                title.clone(),    // Clone to transfer ownership
                username.clone(), 
                cred_password
            );
            
            // Encrypt and persist the credential to the vault.
            // save_credential() handles serialization and encryption.
            db.save_credential(&cred)
                .map_err(|e| anyhow::anyhow!(e.to_string()))?;
            
            // Confirm success to the user.
            println!("Successfully added {} to vault.", title);
        }
        
        // This branch is unreachable because Create is handled earlier,
        // but we need it for exhaustive pattern matching.
        Commands::Create { .. } => unreachable!(),
    }

    // -----------------------------------------------------------------
    // Step 7: Return Success
    // -----------------------------------------------------------------
    // Ok(()) indicates successful execution with no return value.
    // The ? operator above propagates any errors as Err variants.
    Ok(())
}
